version: '3'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    networks:
      - elastic
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms256M -Xmx256M"

  filebeat:
    container_name: filebeat
    image: docker.elastic.co/filebeat/filebeat:7.10.2
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    networks:
      - elastic
    environment:
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    env_file:
      - filebeat.env
    depends_on:
      - elasticsearch
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.10.2
    ports:
      - 127.0.0.1:5601:5601
    networks:
      - elastic
    environment:
      SERVER_NAME: elastic.ottr.one
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch

networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch_data:
    driver: local
